spring.datasource.url=jdbc:postgresql://191.96.153.218:5432/booking_db
spring.datasource.username=postgres
spring.datasource.password=new_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.check-template-location=false

server.port=8080